### ISSUE TITLE
Apply command fails for symlinked path repositories

### ISSUE THREAD

**Issue by mantiz** [covex-nn/extra-flex#1]
Hi,

first of all, thanks for this plugin. I had a similar idea and was more than thankful that someone else did the job. :+1: 

I am playing around some time now and I tried to use the `apply` command to re-apply an embedded recipe which failed. The problem is that the `configurator` is `null` at https://github.com/covex-nn/extra-flex/blob/master/src/Composer/ExtraFlexPlugin.php#L115

I have no experience with composer plugins, so I have no clue where this property should have been set.

I don't know if it makes any difference that I'm using symlinked path repositories for my packages.

Would be great if you have any idea of what is going wrong here and maybe even fix it. :smile: 
Any hint on what may be the problem, so I can try some debugging, would also be very welcome. :wink:

I'll let you know if I find some more information or a solution.

**Comment by covex-nn** [comment]
I did not think that someone would use my plugin! =) But, it is great you use it =)) And i will try fix a bug (i reproduced it with `covex-nn/extra-flex-foobar` package).

Almost everything is private in Flex code, so i had to use Reflection to make it accessible - this is a reason why this plugin is not stable.

To run a plugin, i open two projects with PHPStorm: (1) a project, created with `composer create-project` and required plugin with composer; and (2) a project with plugin itself. Then i create a symlink from plugin project directory to `vendor/covex-nn/extra-flex` of project_(1). Then i update code with PHPStorm in project_(2) and see how in works with project_(1)

To debug it, i run `vendor/composer/composer/bin/composer` script from project_(2) in project directory of project_(1) with some arguments. Also env variable `COMPOSER_ALLOW_XDEBUG=1` must be set to debug with xdebug. And may be my explanation is more complecated, then debugging composer plugin, sorry for that =))

And please, explain what is `symlinked path repositories for packages`

**Comment by mantiz** [comment]
Why shouldn't I use this plugin? It's great for playing around with flex recipes without the need to setup a flex server. :smile: 
I wished this functionality would have been implemented in the flex core.

With `symlinked path repositories` I meant the option to setup local repositories in your `composer.json` using a repository type `path` which is handy when you have kind of a mono-repo.
My test application has a layout like this:
```
+- packages
   +- package-a
   +- package-b
   +- ...
+- test-app
```

`test-app` is a default flex-app created with `composer create-project symfony/skeleton` and I added the following snippet to the `composer.json` of `test-app`:
```
  "repositories": [
    {
      "type": "path",
      "url": "../packages/*",
      "options": {
        "symlink": true
      }
    }
  ]
```
This way I can use my composer packages in multiple flex applications. And with the fix of #2 I can now also update the embedded recipes if needed. :smile:

**Comment by covex-nn** [comment]
I did not know about `"type": "path"` repository =) And thank you for your patch!

Right now i am working on another solution, where i am trying to configure application, instead of configuring packages with recipe. There it will be possible to apply some operations one by one, i.e. set up some default docker environment, or update files, or copy files to app dir. If you use `composer apply`, then i guess, you will like new solution. I will let you know when it will be ready to play with )

**Comment by mantiz** [comment]
Sounds interesting. Yes, please let me know. :)

**Comment by covex-nn** [comment]
@mantiz i guess a new solution is ready to play with =) I created an issue there to show how it works https://github.com/covex-nn/env-configurator/issues/10, please have a look at it. The questions are welcome =)
